apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  config.yaml: |
    ---
    apiVersion: dummy.provider.extensions.config.gardener.cloud/v1alpha1
    kind: ControllerConfiguration
    gardenId: {{ .Values.gardener.garden.identity }}
